export interface FoodDatabaseItem {
  id: string;
  name: string;
  nameBg: string;
  category: 'DAIRY' | 'MEAT_POULTRY' | 'FISH_SEAFOOD' | 'GRAINS_CARBS' | 'VEGETABLES' | 'FRUITS' | 'NUTS_FATS' | 'BULGARIAN_SPECIALTIES' | 'SUPPLEMENTS';
  servingGrams: number;
  servingLabel: string;
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatsPer100g: number;
  popularBgBrand?: string;
}

export const BULGARIAN_AND_GLOBAL_FOODS: FoodDatabaseItem[] = [
  // --- BULGARIAN DAIRY & CHEESES ---
  {
    id: 'bg-sirene-cow',
    name: 'Bulgarian White Cheese (Cow Sirene)',
    nameBg: 'Краве сирене българско',
    category: 'DAIRY',
    servingGrams: 100,
    servingLabel: '100g portion',
    caloriesPer100g: 290,
    proteinPer100g: 17.0,
    carbsPer100g: 1.5,
    fatsPer100g: 24.0,
    popularBgBrand: 'Маджаров / Елена / Сердика',
  },
  {
    id: 'bg-sirene-sheep',
    name: 'Bulgarian Sheep White Cheese (Ovche Sirene)',
    nameBg: 'Овче сирене българско',
    category: 'DAIRY',
    servingGrams: 100,
    servingLabel: '100g portion',
    caloriesPer100g: 330,
    proteinPer100g: 18.5,
    carbsPer100g: 1.0,
    fatsPer100g: 28.0,
    popularBgBrand: 'Родопчанка / Маджаров',
  },
  {
    id: 'bg-kashkaval',
    name: 'Bulgarian Yellow Cheese (Kashkaval Vitosha/Balkan)',
    nameBg: 'Кашкавал Витоша / Балкан',
    category: 'DAIRY',
    servingGrams: 50,
    servingLabel: '50g (2 slices)',
    caloriesPer100g: 340,
    proteinPer100g: 25.0,
    carbsPer100g: 2.0,
    fatsPer100g: 26.0,
    popularBgBrand: 'Верея / Маджаров / Саяна',
  },
  {
    id: 'bg-kiselo-mlyako-2',
    name: 'Bulgarian Yogurt 2% (Kiselo Mlyako)',
    nameBg: 'Кисело мляко 2% Верея',
    category: 'DAIRY',
    servingGrams: 400,
    servingLabel: '1 кофичка (400g)',
    caloriesPer100g: 48,
    proteinPer100g: 3.4,
    carbsPer100g: 4.5,
    fatsPer100g: 2.0,
    popularBgBrand: 'Верея / На Баба / Саяна',
  },
  {
    id: 'bg-kiselo-mlyako-36',
    name: 'Bulgarian Yogurt 3.6% (Kiselo Mlyako)',
    nameBg: 'Кисело мляко 3.6% Верея',
    category: 'DAIRY',
    servingGrams: 400,
    servingLabel: '1 кофичка (400g)',
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbsPer100g: 4.6,
    fatsPer100g: 3.6,
    popularBgBrand: 'Верея / Бор Чвор',
  },
  {
    id: 'bg-kiselo-mlyako-cedeno',
    name: 'Strained Bulgarian Yogurt (Cedeno Mlyako)',
    nameBg: 'Цедено кисело мляко 10%',
    category: 'DAIRY',
    servingGrams: 150,
    servingLabel: '150g portion',
    caloriesPer100g: 130,
    proteinPer100g: 7.5,
    carbsPer100g: 4.0,
    fatsPer100g: 10.0,
    popularBgBrand: 'Олимп / Верея',
  },
  {
    id: 'bg-izkvara',
    name: 'Bulgarian Cottage Cheese / Curd (Izkvara)',
    nameBg: 'Извара нискомаслена (Izkvara)',
    category: 'DAIRY',
    servingGrams: 200,
    servingLabel: '200g portion',
    caloriesPer100g: 85,
    proteinPer100g: 16.5,
    carbsPer100g: 2.5,
    fatsPer100g: 1.0,
    popularBgBrand: 'Олимпус / Пилос / Маджаров',
  },
  {
    id: 'bg-skyr-olympus',
    name: 'Olympus Skyr Natural 0% Fat',
    nameBg: 'Олимпус Скир 0% Натурален',
    category: 'DAIRY',
    servingGrams: 150,
    servingLabel: '1 кофичка (150g)',
    caloriesPer100g: 60,
    proteinPer100g: 11.0,
    carbsPer100g: 4.0,
    fatsPer100g: 0.2,
    popularBgBrand: 'Olympus Skyr',
  },
  {
    id: 'bg-pryasno-mlyako-15',
    name: 'Fresh Cow Milk 1.5% (Pryasno Mlyako)',
    nameBg: 'Прясно мляко 1.5% Верея',
    category: 'DAIRY',
    servingGrams: 250,
    servingLabel: '1 чаша (250ml)',
    caloriesPer100g: 45,
    proteinPer100g: 3.2,
    carbsPer100g: 4.7,
    fatsPer100g: 1.5,
    popularBgBrand: 'Верея / Меггле',
  },

  // --- MEATS, POULTRY & CHARCUTERIE ---
  {
    id: 'meat-chicken-breast',
    name: 'Chicken Breast Fillet (Raw/Cooked)',
    nameBg: 'Пилешко филе гърди (сурово/печено)',
    category: 'MEAT_POULTRY',
    servingGrams: 200,
    servingLabel: '200g fillet',
    caloriesPer100g: 120,
    proteinPer100g: 23.5,
    carbsPer100g: 0.0,
    fatsPer100g: 2.0,
    popularBgBrand: 'Градус / Лудогорско пиле',
  },
  {
    id: 'meat-beef-tenderloin',
    name: 'Lean Beef Tenderloin / Steak',
    nameBg: 'Телешко бонфиле / Телешки шол',
    category: 'MEAT_POULTRY',
    servingGrams: 200,
    servingLabel: '200g steak',
    caloriesPer100g: 145,
    proteinPer100g: 24.0,
    carbsPer100g: 0.0,
    fatsPer100g: 5.5,
    popularBgBrand: 'Българско фермерско месо',
  },
  {
    id: 'meat-pork-tenderloin',
    name: 'Pork Tenderloin (Kontrafile)',
    nameBg: 'Свинско контрафиле печено',
    category: 'MEAT_POULTRY',
    servingGrams: 200,
    servingLabel: '200g portion',
    caloriesPer100g: 140,
    proteinPer100g: 23.0,
    carbsPer100g: 0.0,
    fatsPer100g: 5.0,
    popularBgBrand: 'Тандем / Кен',
  },
  {
    id: 'meat-kyufte-grilled',
    name: 'Bulgarian Grilled Meatball (Kyufte na skara)',
    nameBg: 'Домашно кюфте на скара',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 80,
    servingLabel: '1 брой (80g)',
    caloriesPer100g: 245,
    proteinPer100g: 18.0,
    carbsPer100g: 3.5,
    fatsPer100g: 17.5,
    popularBgBrand: 'Скара / Месарница',
  },
  {
    id: 'meat-kebapche-grilled',
    name: 'Bulgarian Grilled Kebapche',
    nameBg: 'Кебапче на скара',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 80,
    servingLabel: '1 брой (80g)',
    caloriesPer100g: 250,
    proteinPer100g: 17.5,
    carbsPer100g: 2.0,
    fatsPer100g: 19.0,
    popularBgBrand: 'Скара / Месарница',
  },
  {
    id: 'meat-file-elena',
    name: 'Bulgarian Dried Cured Meat (File Elena)',
    nameBg: 'Филе Елена сурово-сушено',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 50,
    servingLabel: '50g (plate)',
    caloriesPer100g: 215,
    proteinPer100g: 34.0,
    carbsPer100g: 1.0,
    fatsPer100g: 8.0,
    popularBgBrand: 'Орехите / Еко Мес / Тандем',
  },
  {
    id: 'meat-lukanka',
    name: 'Bulgarian Traditional Lukanka',
    nameBg: 'Луканка Търновска / Панагюрска',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 50,
    servingLabel: '50g (slices)',
    caloriesPer100g: 410,
    proteinPer100g: 28.0,
    carbsPer100g: 1.5,
    fatsPer100g: 33.0,
    popularBgBrand: 'Орехите / Кен / Братя Къртеви',
  },
  {
    id: 'meat-eggs-boiled',
    name: 'Whole Large Chicken Egg (Boiled/Cooked)',
    nameBg: 'Яйце цяло варено (L размер)',
    category: 'MEAT_POULTRY',
    servingGrams: 60,
    servingLabel: '1 яйце (60g)',
    caloriesPer100g: 155,
    proteinPer100g: 13.0,
    carbsPer100g: 1.1,
    fatsPer100g: 11.0,
    popularBgBrand: 'Яйца Български Фермерски',
  },
  {
    id: 'meat-egg-whites',
    name: 'Liquid / Boiled Egg Whites',
    nameBg: 'Яйчен белтък (пастьоризиран/варен)',
    category: 'MEAT_POULTRY',
    servingGrams: 150,
    servingLabel: '150ml (4-5 белтъка)',
    caloriesPer100g: 52,
    proteinPer100g: 11.0,
    carbsPer100g: 0.7,
    fatsPer100g: 0.2,
    popularBgBrand: 'Egg Whites BG',
  },

  // --- FISH & SEAFOOD ---
  {
    id: 'fish-salmon-fillet',
    name: 'Atlantic Salmon Fillet (Baked/Pan)',
    nameBg: 'Сьомга филе печена',
    category: 'FISH_SEAFOOD',
    servingGrams: 180,
    servingLabel: '180g fillet',
    caloriesPer100g: 208,
    proteinPer100g: 22.0,
    carbsPer100g: 0.0,
    fatsPer100g: 13.0,
    popularBgBrand: 'Fresh Salmon',
  },
  {
    id: 'fish-tuna-canned-water',
    name: 'Canned Tuna in Natural Brine/Water',
    nameBg: 'Риба тон консерва в собствен сос',
    category: 'FISH_SEAFOOD',
    servingGrams: 160,
    servingLabel: '1 консерва (160g)',
    caloriesPer100g: 110,
    proteinPer100g: 25.5,
    carbsPer100g: 0.0,
    fatsPer100g: 0.8,
    popularBgBrand: 'Rio Mare / Calvo / Pilos',
  },
  {
    id: 'fish-trout-grilled',
    name: 'Bulgarian Mountain Trout (Pustarva na skara)',
    nameBg: 'Пъстърва на скара',
    category: 'FISH_SEAFOOD',
    servingGrams: 250,
    servingLabel: '1 цяла риба (250g)',
    caloriesPer100g: 140,
    proteinPer100g: 21.0,
    carbsPer100g: 0.0,
    fatsPer100g: 6.0,
    popularBgBrand: 'Родопска Пъстърва',
  },

  // --- BULGARIAN PREPARED DISHES & SALADS ---
  {
    id: 'bg-shopska-salad',
    name: 'Shopska Salad with Bulgarian Sirene',
    nameBg: 'Шопска салата със сирене',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 300,
    servingLabel: '1 голяма салата (300g)',
    caloriesPer100g: 85,
    proteinPer100g: 4.5,
    carbsPer100g: 4.0,
    fatsPer100g: 6.0,
  },
  {
    id: 'bg-tarator',
    name: 'Bulgarian Cold Tarator Soup',
    nameBg: 'Таратор с орехи и копър',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 300,
    servingLabel: '1 купа (300ml)',
    caloriesPer100g: 50,
    proteinPer100g: 2.8,
    carbsPer100g: 3.2,
    fatsPer100g: 3.0,
  },
  {
    id: 'bg-lyutenitsa',
    name: 'Bulgarian Lyutenitsa (Fine/Coarse)',
    nameBg: 'Лютеница Дерони / Олинеза домашна',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 50,
    servingLabel: '2 с.л. (50g)',
    caloriesPer100g: 135,
    proteinPer100g: 2.2,
    carbsPer100g: 16.0,
    fatsPer100g: 7.0,
    popularBgBrand: 'Дерони / Олинеза / Първомай',
  },
  {
    id: 'bg-bob-chorba',
    name: 'Bulgarian Monastery Bean Soup (Bob Chorba)',
    nameBg: 'Боб чорба по манастирски',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 350,
    servingLabel: '1 купа (350ml)',
    caloriesPer100g: 75,
    proteinPer100g: 4.8,
    carbsPer100g: 12.5,
    fatsPer100g: 1.2,
  },
  {
    id: 'bg-leshta-chorba',
    name: 'Bulgarian Lentil Soup (Leshta)',
    nameBg: 'Леща чорба домашна',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 350,
    servingLabel: '1 купа (350ml)',
    caloriesPer100g: 82,
    proteinPer100g: 5.5,
    carbsPer100g: 13.0,
    fatsPer100g: 1.5,
  },
  {
    id: 'bg-banitsa',
    name: 'Bulgarian Homemade Banitsa with Cheese',
    nameBg: 'Баница със сирене и яйца',
    category: 'BULGARIAN_SPECIALTIES',
    servingGrams: 150,
    servingLabel: '1 парче (150g)',
    caloriesPer100g: 295,
    proteinPer100g: 9.5,
    carbsPer100g: 27.0,
    fatsPer100g: 16.5,
    popularBgBrand: 'Белла / Фамилия',
  },

  // --- GRAINS, CARBOHYDRATES & STARCHES ---
  {
    id: 'carb-oats-rolled',
    name: 'Fine Rolled Oats (Oveseni Yadki)',
    nameBg: 'Овесени ядки фини',
    category: 'GRAINS_CARBS',
    servingGrams: 80,
    servingLabel: '1 купа (80g)',
    caloriesPer100g: 375,
    proteinPer100g: 13.5,
    carbsPer100g: 62.0,
    fatsPer100g: 7.0,
    popularBgBrand: 'Фитнес / Крина',
  },
  {
    id: 'carb-white-rice-basmati',
    name: 'White Basmati / Jasmine Rice (Cooked)',
    nameBg: 'Бял ориз Басмати / Бисерен (сварен)',
    category: 'GRAINS_CARBS',
    servingGrams: 200,
    servingLabel: '1 чаша с връх (200g)',
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28.5,
    fatsPer100g: 0.3,
    popularBgBrand: 'Крина / Оберст',
  },
  {
    id: 'carb-potatoes-baked',
    name: 'Baked / Boiled Potatoes',
    nameBg: 'Картофи печени / варени',
    category: 'GRAINS_CARBS',
    servingGrams: 250,
    servingLabel: '2 средни картофа (250g)',
    caloriesPer100g: 87,
    proteinPer100g: 2.0,
    carbsPer100g: 20.0,
    fatsPer100g: 0.1,
  },
  {
    id: 'carb-sweet-potatoes',
    name: 'Sweet Potatoes (Sladki Kartofi)',
    nameBg: 'Сладки картофи (батат) печени',
    category: 'GRAINS_CARBS',
    servingGrams: 200,
    servingLabel: '200g portion',
    caloriesPer100g: 90,
    proteinPer100g: 2.0,
    carbsPer100g: 21.0,
    fatsPer100g: 0.15,
  },
  {
    id: 'carb-bread-vita',
    name: 'Bulgarian Whole Grain Bread (Hlyab Vita 100%)',
    nameBg: 'Хляб Вита 100% Пълнозърнест',
    category: 'GRAINS_CARBS',
    servingGrams: 70,
    servingLabel: '2 филии (70g)',
    caloriesPer100g: 210,
    proteinPer100g: 10.5,
    carbsPer100g: 38.0,
    fatsPer100g: 1.8,
    popularBgBrand: 'Вита / Бонус',
  },
  {
    id: 'carb-pasta-wholewheat',
    name: 'Wholewheat Pasta / Macaroni (Cooked)',
    nameBg: 'Пълнозърнеста паста / Макарони (сварени)',
    category: 'GRAINS_CARBS',
    servingGrams: 200,
    servingLabel: '200g portion',
    caloriesPer100g: 124,
    proteinPer100g: 5.3,
    carbsPer100g: 25.0,
    fatsPer100g: 0.8,
    popularBgBrand: 'Barilla Integrale',
  },

  // --- FRUITS & HEALTHY FATS ---
  {
    id: 'fruit-banana',
    name: 'Fresh Banana (Banan)',
    nameBg: 'Банан пресен',
    category: 'FRUITS',
    servingGrams: 120,
    servingLabel: '1 среден банан (120g)',
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23.0,
    fatsPer100g: 0.3,
  },
  {
    id: 'fruit-apple',
    name: 'Fresh Crisp Apple (Yabalka)',
    nameBg: 'Ябълка домашна',
    category: 'FRUITS',
    servingGrams: 150,
    servingLabel: '1 средна ябълка (150g)',
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14.0,
    fatsPer100g: 0.2,
  },
  {
    id: 'fruit-blueberries',
    name: 'Wild Blueberries (Borovinki)',
    nameBg: 'Горски боровинки',
    category: 'FRUITS',
    servingGrams: 100,
    servingLabel: '1 купа (100g)',
    caloriesPer100g: 57,
    proteinPer100g: 0.7,
    carbsPer100g: 14.5,
    fatsPer100g: 0.3,
  },
  {
    id: 'fat-avocado',
    name: 'Ripe Avocado Hass',
    nameBg: 'Авокадо Хас',
    category: 'NUTS_FATS',
    servingGrams: 100,
    servingLabel: '1/2 авокадо (100g)',
    caloriesPer100g: 160,
    proteinPer100g: 2.0,
    carbsPer100g: 8.5,
    fatsPer100g: 15.0,
  },
  {
    id: 'fat-almonds-raw',
    name: 'Raw Almonds (Surovi Bademi)',
    nameBg: 'Сурови бадеми',
    category: 'NUTS_FATS',
    servingGrams: 30,
    servingLabel: '1 шепа (30g)',
    caloriesPer100g: 580,
    proteinPer100g: 21.0,
    carbsPer100g: 20.0,
    fatsPer100g: 50.0,
  },
  {
    id: 'fat-olive-oil',
    name: 'Extra Virgin Olive Oil (Zextin)',
    nameBg: 'Зехтин Екстра Върджин',
    category: 'NUTS_FATS',
    servingGrams: 14,
    servingLabel: '1 с.л. (14g)',
    caloriesPer100g: 884,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatsPer100g: 100.0,
    popularBgBrand: 'Minerva / Borges',
  },
  {
    id: 'fat-peanut-butter',
    name: '100% Pure Peanut Butter (Fastacheno maslo)',
    nameBg: 'Фъстъчено масло 100% натурално',
    category: 'NUTS_FATS',
    servingGrams: 32,
    servingLabel: '2 с.л. (32g)',
    caloriesPer100g: 590,
    proteinPer100g: 26.0,
    carbsPer100g: 16.0,
    fatsPer100g: 49.0,
    popularBgBrand: 'VikiNuts / GymBeam',
  },

  // --- SPORTS SUPPLEMENTS & PROTEIN SNACKS ---
  {
    id: 'supp-whey-isolate',
    name: '100% Whey Protein Isolate Powder',
    nameBg: 'Суроватъчен протеин изолат (1 доза)',
    category: 'SUPPLEMENTS',
    servingGrams: 30,
    servingLabel: '1 мерителна лъжица (30g)',
    caloriesPer100g: 380,
    proteinPer100g: 83.3,
    carbsPer100g: 3.3,
    fatsPer100g: 3.3,
    popularBgBrand: 'Optimum Nutrition / Biotech / Applied Nutrition',
  },
  {
    id: 'supp-fitspo-bar',
    name: 'FitSpo Max Protein Bar (Bulgarian 70g)',
    nameBg: 'FitSpo Max Протеинов бар 70g (30g протеин)',
    category: 'SUPPLEMENTS',
    servingGrams: 70,
    servingLabel: '1 бар (70g)',
    caloriesPer100g: 370,
    proteinPer100g: 42.8,
    carbsPer100g: 28.5,
    fatsPer100g: 11.4,
    popularBgBrand: 'FitSpo Bulgaria',
  },
  {
    id: 'supp-barebells-bar',
    name: 'Barebells Protein Bar',
    nameBg: 'Barebells Protein Bar 55g',
    category: 'SUPPLEMENTS',
    servingGrams: 55,
    servingLabel: '1 бар (55g)',
    caloriesPer100g: 360,
    proteinPer100g: 36.3,
    carbsPer100g: 29.0,
    fatsPer100g: 15.0,
  },
  // --- VEGETABLES ---
  {
    id: 'veg-broccoli',
    name: 'Broccoli steamed',
    nameBg: 'Броколи задушено',
    category: 'VEGETABLES',
    servingGrams: 200,
    servingLabel: '200g portion',
    caloriesPer100g: 34,
    proteinPer100g: 2.8,
    carbsPer100g: 6.6,
    fatsPer100g: 0.4,
  },
  {
    id: 'veg-spinach',
    name: 'Baby Spinach raw',
    nameBg: 'Спанак пресен',
    category: 'VEGETABLES',
    servingGrams: 100,
    servingLabel: '100g',
    caloriesPer100g: 23,
    proteinPer100g: 2.9,
    carbsPer100g: 3.6,
    fatsPer100g: 0.4,
  },
  {
    id: 'veg-zucchini',
    name: 'Zucchini grilled',
    nameBg: 'Тиквички на скара',
    category: 'VEGETABLES',
    servingGrams: 200,
    servingLabel: '200g',
    caloriesPer100g: 17,
    proteinPer100g: 1.2,
    carbsPer100g: 3.1,
    fatsPer100g: 0.3,
  },
  {
    id: 'veg-peppers-red',
    name: 'Red Bell Pepper raw',
    nameBg: 'Червен пипер пресен',
    category: 'VEGETABLES',
    servingGrams: 150,
    servingLabel: '1 голям пипер (150g)',
    caloriesPer100g: 31,
    proteinPer100g: 1.0,
    carbsPer100g: 7.0,
    fatsPer100g: 0.3,
  },
  {
    id: 'veg-tomatoes',
    name: 'Tomatoes fresh',
    nameBg: 'Домати пресни',
    category: 'VEGETABLES',
    servingGrams: 200,
    servingLabel: '2 средни домата (200g)',
    caloriesPer100g: 18,
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatsPer100g: 0.2,
  },
  {
    id: 'veg-cucumber',
    name: 'Cucumber fresh',
    nameBg: 'Краставица пресна',
    category: 'VEGETABLES',
    servingGrams: 200,
    servingLabel: '1 краставица (200g)',
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatsPer100g: 0.1,
  },
  {
    id: 'veg-cauliflower',
    name: 'Cauliflower roasted',
    nameBg: 'Карфиол печен',
    category: 'VEGETABLES',
    servingGrams: 200,
    servingLabel: '200g',
    caloriesPer100g: 25,
    proteinPer100g: 1.9,
    carbsPer100g: 5.0,
    fatsPer100g: 0.3,
  },
  {
    id: 'veg-onion',
    name: 'Yellow Onion',
    nameBg: 'Лук жълт',
    category: 'VEGETABLES',
    servingGrams: 100,
    servingLabel: '1 среден лук (100g)',
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbsPer100g: 9.3,
    fatsPer100g: 0.1,
  },
  {
    id: 'veg-green-beans',
    name: 'Green beans steamed',
    nameBg: 'Зелен фасул задушен',
    category: 'VEGETABLES',
    servingGrams: 150,
    servingLabel: '150g',
    caloriesPer100g: 31,
    proteinPer100g: 1.8,
    carbsPer100g: 7.1,
    fatsPer100g: 0.1,
  },
  {
    id: 'veg-carrots',
    name: 'Carrots boiled',
    nameBg: 'Моркови варени',
    category: 'VEGETABLES',
    servingGrams: 150,
    servingLabel: '150g',
    caloriesPer100g: 35,
    proteinPer100g: 0.8,
    carbsPer100g: 8.2,
    fatsPer100g: 0.2,
  },
  // --- MORE FRUITS ---
  {
    id: 'fruit-strawberries',
    name: 'Fresh Strawberries',
    nameBg: 'Ягоди пресни',
    category: 'FRUITS',
    servingGrams: 150,
    servingLabel: '1 купа (150g)',
    caloriesPer100g: 32,
    proteinPer100g: 0.7,
    carbsPer100g: 7.7,
    fatsPer100g: 0.3,
  },
  {
    id: 'fruit-orange',
    name: 'Fresh Orange',
    nameBg: 'Портокал пресен',
    category: 'FRUITS',
    servingGrams: 180,
    servingLabel: '1 голям портокал (180g)',
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 11.8,
    fatsPer100g: 0.1,
  },
  {
    id: 'fruit-grapes',
    name: 'Red or Green Grapes',
    nameBg: 'Грозде червено / зелено',
    category: 'FRUITS',
    servingGrams: 150,
    servingLabel: '1 грозд (150g)',
    caloriesPer100g: 69,
    proteinPer100g: 0.7,
    carbsPer100g: 18.1,
    fatsPer100g: 0.2,
  },
  {
    id: 'fruit-kiwi',
    name: 'Kiwi fruit',
    nameBg: 'Киви пресно',
    category: 'FRUITS',
    servingGrams: 100,
    servingLabel: '1 киви (100g)',
    caloriesPer100g: 61,
    proteinPer100g: 1.1,
    carbsPer100g: 14.7,
    fatsPer100g: 0.5,
  },
  {
    id: 'fruit-watermelon',
    name: 'Watermelon slice',
    nameBg: 'Диня',
    category: 'FRUITS',
    servingGrams: 300,
    servingLabel: '1 голяма резен (300g)',
    caloriesPer100g: 30,
    proteinPer100g: 0.6,
    carbsPer100g: 7.6,
    fatsPer100g: 0.2,
  },
  // --- MORE GRAINS ---
  {
    id: 'carb-quinoa',
    name: 'Quinoa cooked',
    nameBg: 'Киноа сварена',
    category: 'GRAINS_CARBS',
    servingGrams: 185,
    servingLabel: '1 чаша сварена (185g)',
    caloriesPer100g: 120,
    proteinPer100g: 4.4,
    carbsPer100g: 21.3,
    fatsPer100g: 1.9,
    popularBgBrand: 'Krина / Здравец',
  },
  {
    id: 'carb-brown-rice',
    name: 'Brown rice cooked',
    nameBg: 'Кафяв ориз сварен',
    category: 'GRAINS_CARBS',
    servingGrams: 200,
    servingLabel: '200g сварен',
    caloriesPer100g: 110,
    proteinPer100g: 2.6,
    carbsPer100g: 23.0,
    fatsPer100g: 0.9,
  },
  {
    id: 'carb-buckwheat',
    name: 'Buckwheat groats cooked',
    nameBg: 'Елда сварена (Хречка)',
    category: 'GRAINS_CARBS',
    servingGrams: 200,
    servingLabel: '200g',
    caloriesPer100g: 92,
    proteinPer100g: 3.4,
    carbsPer100g: 20.0,
    fatsPer100g: 0.6,
  },
  {
    id: 'carb-corn-tortilla',
    name: 'Corn tortilla wrap',
    nameBg: 'Царевична тортила',
    category: 'GRAINS_CARBS',
    servingGrams: 45,
    servingLabel: '1 бр (45g)',
    caloriesPer100g: 218,
    proteinPer100g: 5.7,
    carbsPer100g: 44.6,
    fatsPer100g: 2.6,
  },
  {
    id: 'carb-lentils-cooked',
    name: 'Red lentils cooked',
    nameBg: 'Червена леща сварена',
    category: 'GRAINS_CARBS',
    servingGrams: 200,
    servingLabel: '200g',
    caloriesPer100g: 116,
    proteinPer100g: 9.0,
    carbsPer100g: 20.1,
    fatsPer100g: 0.4,
  },
  {
    id: 'carb-chickpeas',
    name: 'Chickpeas cooked / canned',
    nameBg: 'Нахут сварен / консерва',
    category: 'GRAINS_CARBS',
    servingGrams: 150,
    servingLabel: '150g',
    caloriesPer100g: 164,
    proteinPer100g: 8.9,
    carbsPer100g: 27.4,
    fatsPer100g: 2.6,
    popularBgBrand: 'Bonduelle / Domo',
  },
  // --- MORE MEAT & FISH ---
  {
    id: 'meat-turkey-breast',
    name: 'Turkey breast grilled',
    nameBg: 'Пуешко гърди печено',
    category: 'MEAT_POULTRY',
    servingGrams: 180,
    servingLabel: '180g',
    caloriesPer100g: 135,
    proteinPer100g: 29.0,
    carbsPer100g: 0.0,
    fatsPer100g: 1.8,
  },
  {
    id: 'meat-chicken-thigh',
    name: 'Chicken thigh skinless baked',
    nameBg: 'Пилешко бутче без кожа, печено',
    category: 'MEAT_POULTRY',
    servingGrams: 150,
    servingLabel: '1 бутче (150g)',
    caloriesPer100g: 155,
    proteinPer100g: 21.0,
    carbsPer100g: 0.0,
    fatsPer100g: 7.5,
  },
  {
    id: 'fish-sardines-can',
    name: 'Canned sardines in olive oil',
    nameBg: 'Сардини в зехтин (консерва)',
    category: 'FISH_SEAFOOD',
    servingGrams: 120,
    servingLabel: '1 консерва (120g)',
    caloriesPer100g: 208,
    proteinPer100g: 21.5,
    carbsPer100g: 0.0,
    fatsPer100g: 13.5,
    popularBgBrand: 'Rio Mare / Ribela',
  },
  {
    id: 'fish-mackerel-smoked',
    name: 'Smoked mackerel fillet',
    nameBg: 'Пушена скумрия филе',
    category: 'FISH_SEAFOOD',
    servingGrams: 100,
    servingLabel: '100g',
    caloriesPer100g: 245,
    proteinPer100g: 19.0,
    carbsPer100g: 0.0,
    fatsPer100g: 18.5,
  },
  {
    id: 'fish-cod-baked',
    name: 'Cod fillet baked',
    nameBg: 'Треска филе печена',
    category: 'FISH_SEAFOOD',
    servingGrams: 180,
    servingLabel: '180g',
    caloriesPer100g: 82,
    proteinPer100g: 18.0,
    carbsPer100g: 0.0,
    fatsPer100g: 0.7,
  },
  {
    id: 'fish-shrimp-grilled',
    name: 'Grilled shrimp / prawns',
    nameBg: 'Скариди на скара',
    category: 'FISH_SEAFOOD',
    servingGrams: 150,
    servingLabel: '150g',
    caloriesPer100g: 99,
    proteinPer100g: 20.5,
    carbsPer100g: 0.9,
    fatsPer100g: 1.1,
  },
  // --- MORE NUTS & FATS ---
  {
    id: 'fat-walnuts',
    name: 'Walnuts raw',
    nameBg: 'Орехи сурови',
    category: 'NUTS_FATS',
    servingGrams: 30,
    servingLabel: '1 шепа (30g)',
    caloriesPer100g: 654,
    proteinPer100g: 15.2,
    carbsPer100g: 13.7,
    fatsPer100g: 65.2,
    popularBgBrand: 'Родопски орехи',
  },
  {
    id: 'fat-cashews',
    name: 'Raw cashews',
    nameBg: 'Кашу сурово',
    category: 'NUTS_FATS',
    servingGrams: 30,
    servingLabel: '1 шепа (30g)',
    caloriesPer100g: 553,
    proteinPer100g: 18.2,
    carbsPer100g: 30.2,
    fatsPer100g: 43.8,
  },
  {
    id: 'fat-tahini',
    name: 'Tahini sesame paste',
    nameBg: 'Тахан (сусамов тахини)',
    category: 'NUTS_FATS',
    servingGrams: 30,
    servingLabel: '2 с.л. (30g)',
    caloriesPer100g: 595,
    proteinPer100g: 17.0,
    carbsPer100g: 21.2,
    fatsPer100g: 53.8,
    popularBgBrand: 'Тахан Здравец',
  },
  {
    id: 'fat-coconut-oil',
    name: 'Coconut oil virgin',
    nameBg: 'Кокосово масло',
    category: 'NUTS_FATS',
    servingGrams: 14,
    servingLabel: '1 с.л. (14g)',
    caloriesPer100g: 862,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatsPer100g: 100.0,
  },
  // --- MORE DAIRY ---
  {
    id: 'dairy-cottage-cheese-low',
    name: 'Low-fat cottage cheese',
    nameBg: 'Извара обезмаслена 0.5%',
    category: 'DAIRY',
    servingGrams: 200,
    servingLabel: '200g',
    caloriesPer100g: 72,
    proteinPer100g: 12.5,
    carbsPer100g: 3.4,
    fatsPer100g: 0.5,
  },
  {
    id: 'dairy-feta-greek',
    name: 'Greek Feta cheese',
    nameBg: 'Гръцка фета',
    category: 'DAIRY',
    servingGrams: 50,
    servingLabel: '50g',
    caloriesPer100g: 264,
    proteinPer100g: 14.2,
    carbsPer100g: 4.1,
    fatsPer100g: 21.3,
    popularBgBrand: 'Athos / Kolios',
  },
  {
    id: 'dairy-mozzarella-low',
    name: 'Low-fat mozzarella',
    nameBg: 'Моцарела нискомаслена',
    category: 'DAIRY',
    servingGrams: 80,
    servingLabel: '80g',
    caloriesPer100g: 190,
    proteinPer100g: 18.0,
    carbsPer100g: 2.2,
    fatsPer100g: 12.5,
    popularBgBrand: 'Galbani / Granarolo',
  },
  // --- MORE SUPPLEMENTS ---
  {
    id: 'supp-creatine',
    name: 'Creatine Monohydrate powder',
    nameBg: 'Креатин монохидрат (5g доза)',
    category: 'SUPPLEMENTS',
    servingGrams: 5,
    servingLabel: '1 доза (5g)',
    caloriesPer100g: 0,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatsPer100g: 0.0,
    popularBgBrand: 'GymBeam / Biotech / Weider',
  },
  {
    id: 'supp-greek-yogurt-0',
    name: 'Greek yogurt 0% protein-rich',
    nameBg: 'Гръцко кисело мляко 0%',
    category: 'DAIRY',
    servingGrams: 200,
    servingLabel: '200g',
    caloriesPer100g: 59,
    proteinPer100g: 10.0,
    carbsPer100g: 3.6,
    fatsPer100g: 0.4,
    popularBgBrand: 'FAGE 0% / Chobani',
  },
];

export function searchFoods(query: string): FoodDatabaseItem[] {
  if (!query || query.trim() === '') return BULGARIAN_AND_GLOBAL_FOODS.slice(0, 15);
  const q = query.toLowerCase().trim();
  return BULGARIAN_AND_GLOBAL_FOODS.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      item.nameBg.toLowerCase().includes(q) ||
      (item.popularBgBrand && item.popularBgBrand.toLowerCase().includes(q)) ||
      item.category.toLowerCase().includes(q)
  );
}
